"""Drift guard for the generated sbp output-schema reference doc.

``docs/SBP_OUTPUT_SCHEMAS.md`` documents the JSON shape of every ``sbp`` output
surface agents parse (``sbp capabilities`` / ``skills`` / ``candidates`` / ``mcp``
/ ``recalibrate`` / ``explain`` / ``doctor`` + ``fleet converge``). The page is GENERATED by
``scripts/gen_output_schemas.py`` from the deterministic ``tests/fixture_fleet.py``
estate, so the example payloads cannot drift from the runtime. This test locks the
committed file to what the generator produces right now: if a payload function
grows/renames/drops a field, the example diff (and any new field without a
stability note) makes the doc fail here until it is regenerated and reviewed.

Mirrors the REGEN pattern in ``tests/test_context_drift_goldens.py``. Regenerate
the committed doc intentionally with::

    REGEN_OUTPUT_SCHEMA_DOCS=1 python3 -m pytest tests/test_output_schema_docs.py

The same run then re-asserts the file equals the freshly generated output, so a
green run after regeneration confirms the new doc is internally consistent.
"""

from __future__ import annotations

import importlib.util
import os
import sys
import unittest
from pathlib import Path


ROOT_DIR = Path(__file__).resolve().parent.parent
SCRIPTS_DIR = ROOT_DIR / "scripts"
ENV_MANAGER_DIR = ROOT_DIR / ".env-manager"
for _path in (SCRIPTS_DIR, ENV_MANAGER_DIR, ROOT_DIR / "tests"):
    if str(_path) not in sys.path:
        sys.path.insert(0, str(_path))


def _load_generator():
    """Import the generator by path (scripts/ is not a package)."""
    spec = importlib.util.spec_from_file_location(
        "gen_output_schemas", SCRIPTS_DIR / "gen_output_schemas.py"
    )
    assert spec and spec.loader
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


GEN = _load_generator()
REGEN_ENV = "REGEN_OUTPUT_SCHEMA_DOCS"

# The eight surfaces this doc must document (the bead's required set).
REQUIRED_SURFACES = {
    "sbp capabilities",
    "sbp skills",
    "sbp candidates",
    "sbp mcp",
    "sbp recalibrate",
    "sbp explain",
    "sbp doctor",
    "fleet converge",
}


class OutputSchemaDocDriftTests(unittest.TestCase):
    maxDiff = None
    _regen = bool(os.environ.get(REGEN_ENV))

    def test_committed_doc_matches_generator(self) -> None:
        rendered = GEN.render_doc()
        path = GEN.DOC_PATH
        if self._regen:
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(rendered, encoding="utf-8")
        self.assertTrue(
            path.is_file(),
            f"Missing generated doc {path}. Regenerate with "
            f"{REGEN_ENV}=1 python3 -m pytest tests/test_output_schema_docs.py",
        )
        committed = path.read_text(encoding="utf-8")
        self.assertEqual(
            committed,
            rendered,
            "docs/SBP_OUTPUT_SCHEMAS.md is stale vs scripts/gen_output_schemas.py. "
            f"If a payload shape changed intentionally, regenerate with {REGEN_ENV}=1 "
            "and review the diff.",
        )

    def test_generator_is_deterministic(self) -> None:
        # The whole point: the doc must be byte-stable across runs (no timestamps,
        # no host paths, no wall-clock durations leaking in).
        self.assertEqual(GEN.render_doc(), GEN.render_doc())

    def test_all_required_surfaces_are_documented(self) -> None:
        commands = {surface["command"] for surface in GEN.SURFACES}
        self.assertEqual(
            commands,
            REQUIRED_SURFACES,
            "The doc must document exactly the required sbp output surfaces.",
        )
        rendered = GEN.render_doc()
        for command in REQUIRED_SURFACES:
            self.assertIn(f"## `{command}`", rendered, command)
        # One example payload per surface.
        self.assertEqual(
            rendered.count("### Example payload"),
            len(REQUIRED_SURFACES),
            "Each surface must carry exactly one example payload.",
        )

    def test_every_documented_field_has_a_stability_note(self) -> None:
        # A field present in a generated example with no FIELD_NOTES entry renders
        # the loud TODO marker; assert it never reaches the committed doc.
        rendered = GEN.render_doc()
        self.assertNotIn("MISSING STABILITY NOTE", rendered)
        self.assertNotIn("| `???`", rendered)

    def test_generated_doc_carries_do_not_hand_edit_banner(self) -> None:
        committed = GEN.DOC_PATH.read_text(encoding="utf-8")
        self.assertIn("GENERATED FILE", committed)
        self.assertIn("do not hand-edit", committed)

    def test_recalibrate_example_includes_machine_actionable_fixes(self) -> None:
        example = GEN.example_recalibrate()
        self.assertIn("fixes", example)
        self.assertTrue(example["fixes"])
        fix = example["fixes"][0]
        for key in (
            "problem",
            "skill",
            "command",
            "links",
            "dry_run_preview",
            "packet_on_apply",
        ):
            with self.subTest(field=key):
                self.assertIn(key, fix)
        self.assertEqual(fix["problem"], "missing_for_cwd")
        self.assertEqual(fix["skill"], "tiny-ui")
        self.assertEqual(fix["command"], "sbp skill on tiny-ui --cwd $PWD")
        self.assertTrue(fix["links"])
        self.assertIsInstance(fix["dry_run_preview"], dict)
        self.assertIsInstance(fix["packet_on_apply"], dict)


if __name__ == "__main__":
    unittest.main()
