"""Canonical Skillbox DCG policy: fail-closed defaults + bounded overlays.

This module is the SINGLE SOURCE OF TRUTH for the contents of ``.dcg.toml``.
It replaces ad-hoc string building with a versioned policy that is:

* **fail-closed by default** -- ``[general] fail_closed = true`` so unparseable
  hook input is DENIED rather than upstream's fail-open default. Turning it off
  requires an *audited exception* (ticket + approver + expiry + reason); an
  unaudited ``fail_closed = false`` is a hard validation error.
* **closed over an approved pack set** -- overlays may only ADD packs that
  appear in :data:`APPROVED_PACKS`. An unknown or typo'd pack id is rejected
  instead of being silently written into a config dcg happily ignores.
* **narrow on allowlists** -- there is NO permissive default allowlist, and a
  rule that is effectively a wildcard (or a rule list past
  :data:`MAX_ALLOWLIST_RULES`) is rejected rather than shipped.
* **deterministic** -- rendering the same policy twice is byte-identical. Pack
  order is defaults-first then overlay order, deduped first-wins; no
  timestamps, hostnames, or absolute paths ever enter the output.

The rendered document deliberately uses only the upstream keys pinned in
:data:`UPSTREAM_KEY_PATHS`. ``dcg`` is lenient -- it silently ignores unknown
tables (the legacy ``[allowlist] rules = [...]`` block this module replaces was
never read by dcg at all) -- so drift is caught here, by validation, not by
hoping the binary complains.

CLI::

    python3 -m runtime_manager.dcg_policy render --output .dcg.toml --format json
    python3 -m runtime_manager.dcg_policy render --overlay client.json
    python3 -m runtime_manager.dcg_policy validate --config .dcg.toml
"""
from __future__ import annotations

import argparse
import json
import sys
import tomllib
from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Any, Iterable, Mapping, Sequence

from .errors import SkillboxError, ValidationError


POLICY_VERSION = 1

# Ownership marker preserved verbatim from the legacy renderer so an existing
# .dcg.toml is still recognizable as generated (and never hand-edited).
GENERATED_MARKER = "# Auto-generated by skillbox runtime manager. Do not edit manually."
POLICY_MARKER = (
    f"# skillbox-dcg-policy v{POLICY_VERSION} - regenerate: "
    "python3 -m runtime_manager.dcg_policy render --output .dcg.toml"
)

# The floor. These are always enabled, always first, and no overlay can drop
# them: git + filesystem are the packs that make dcg worth running at all.
DEFAULT_PACKS: tuple[str, ...] = ("core.git", "core.filesystem")

# Bounded set of packs an overlay is allowed to add. Adding an entry here is a
# POLICY REVIEW, not a config change: every id must exist upstream (the test
# suite cross-checks this against `dcg packs --format json` when the binary is
# present) and must be one Skillbox actually deploys against.
APPROVED_PACKS: frozenset[str] = frozenset(
    {
        # Floor.
        "core.git",
        "core.filesystem",
        # Catastrophic disk ops; default-on upstream, explicit here.
        "system.disk",
        "system.permissions",
        "system.services",
        # Skillbox boxes are container-first.
        "containers.docker",
        "containers.compose",
        "containers.podman",
        # Datastores that appear in box profiles.
        "database.postgresql",
        "database.sqlite",
        "database.redis",
        # Fleet/deploy surfaces.
        "kubernetes.kubectl",
        "infrastructure.terraform",
        "remote.rsync",
        "remote.ssh",
        # Publish paths that can unpublish/yank.
        "package_managers",
        # Paranoid git for repos that want it.
        "strict_git",
    }
)

# An allowlist is an escape hatch, not a configuration surface. Past this many
# rules it is a de-facto disablement of the guard.
MAX_ALLOWLIST_RULES = 16

# Minimum literal (alphanumeric) anchor characters a rule must carry. A rule
# built only from regex metacharacters matches everything.
MIN_ALLOWLIST_ANCHOR_CHARS = 3

MAX_ALLOWLIST_RULE_LENGTH = 200

# Overlay keys we accept. Anything else is a malformed overlay, not a hint.
OVERLAY_KEYS: frozenset[str] = frozenset(
    {"id", "packs", "allowlist", "fail_closed", "fail_closed_exception"}
)

# Fields an audited fail-open exception must carry, all non-empty.
EXCEPTION_FIELDS: tuple[str, ...] = ("ticket", "approved_by", "expires", "reason")

# Every table/key this module is allowed to emit, pinned against upstream's
# config schema. A rendered doc touching anything else is a syntax mismatch.
UPSTREAM_KEY_PATHS: frozenset[tuple[str, ...]] = frozenset(
    {
        ("general", "fail_closed"),
        ("packs", "enabled"),
        ("overrides", "allow"),
    }
)

# Stable machine codes. Kept in one tuple so tests can enumerate them.
DCG_POLICY_UNKNOWN_PACK = "DCG_POLICY_UNKNOWN_PACK"
DCG_POLICY_MALFORMED_PACK = "DCG_POLICY_MALFORMED_PACK"
DCG_POLICY_MALFORMED_ALLOWLIST = "DCG_POLICY_MALFORMED_ALLOWLIST"
DCG_POLICY_BROAD_ALLOWLIST = "DCG_POLICY_BROAD_ALLOWLIST"
DCG_POLICY_MALFORMED_OVERLAY = "DCG_POLICY_MALFORMED_OVERLAY"
DCG_POLICY_UNAUDITED_FAIL_OPEN = "DCG_POLICY_UNAUDITED_FAIL_OPEN"
DCG_POLICY_EXPIRED_EXCEPTION = "DCG_POLICY_EXPIRED_EXCEPTION"
DCG_POLICY_UPSTREAM_MISMATCH = "DCG_POLICY_UPSTREAM_MISMATCH"

DCG_POLICY_ERROR_CODES: tuple[str, ...] = (
    DCG_POLICY_BROAD_ALLOWLIST,
    DCG_POLICY_EXPIRED_EXCEPTION,
    DCG_POLICY_MALFORMED_ALLOWLIST,
    DCG_POLICY_MALFORMED_OVERLAY,
    DCG_POLICY_MALFORMED_PACK,
    DCG_POLICY_UNAUDITED_FAIL_OPEN,
    DCG_POLICY_UNKNOWN_PACK,
    DCG_POLICY_UPSTREAM_MISMATCH,
)


@dataclass(frozen=True)
class FailOpenException:
    """Audited justification for running with ``fail_closed = false``."""

    ticket: str
    approved_by: str
    expires: str
    reason: str

    def to_payload(self) -> dict[str, str]:
        return {
            "ticket": self.ticket,
            "approved_by": self.approved_by,
            "expires": self.expires,
            "reason": self.reason,
        }


@dataclass(frozen=True)
class DcgPolicy:
    """A validated, render-ready DCG policy."""

    packs: tuple[str, ...]
    allowlist: tuple[str, ...]
    fail_closed: bool
    exception: FailOpenException | None = None
    version: int = POLICY_VERSION

    def to_payload(self) -> dict[str, Any]:
        payload: dict[str, Any] = {
            "version": self.version,
            "fail_closed": self.fail_closed,
            "packs": list(self.packs),
            "allowlist": list(self.allowlist),
        }
        if self.exception is not None:
            payload["fail_closed_exception"] = self.exception.to_payload()
        return payload


# ---------------------------------------------------------------------------
# Validation helpers
# ---------------------------------------------------------------------------


def _reject(code: str, message: str, **context: Any) -> ValidationError:
    return ValidationError(
        code,
        message,
        context={key: value for key, value in context.items() if value is not None},
        next_actions=[
            "Fix the overlay, or extend APPROVED_PACKS via policy review.",
            "Re-render: python3 -m runtime_manager.dcg_policy render --output .dcg.toml",
        ],
        recoverable=False,
    )


def _normalize_pack(raw: Any, *, source: str) -> str:
    if not isinstance(raw, str):
        raise _reject(
            DCG_POLICY_MALFORMED_PACK,
            f"DCG pack entries must be strings; {source} supplied {type(raw).__name__}.",
            source=source,
            pack=repr(raw),
        )
    pack = raw.strip()
    if not pack:
        raise _reject(
            DCG_POLICY_MALFORMED_PACK,
            f"DCG pack entries must be non-empty; {source} supplied a blank entry.",
            source=source,
        )
    if pack not in APPROVED_PACKS:
        raise _reject(
            DCG_POLICY_UNKNOWN_PACK,
            f"DCG pack {pack!r} from {source} is not in the approved pack set.",
            source=source,
            pack=pack,
            approved=sorted(APPROVED_PACKS),
        )
    return pack


def _normalize_allowlist_rule(raw: Any, *, source: str) -> str:
    if not isinstance(raw, str):
        raise _reject(
            DCG_POLICY_MALFORMED_ALLOWLIST,
            f"DCG allowlist rules must be strings; {source} supplied {type(raw).__name__}.",
            source=source,
            rule=repr(raw),
        )
    rule = raw.strip()
    if not rule:
        raise _reject(
            DCG_POLICY_MALFORMED_ALLOWLIST,
            f"DCG allowlist rules must be non-empty; {source} supplied a blank rule.",
            source=source,
        )
    if len(rule) > MAX_ALLOWLIST_RULE_LENGTH:
        raise _reject(
            DCG_POLICY_MALFORMED_ALLOWLIST,
            f"DCG allowlist rule from {source} exceeds "
            f"{MAX_ALLOWLIST_RULE_LENGTH} characters.",
            source=source,
            length=len(rule),
        )
    if any(char in rule for char in "\n\r\t") or not rule.isprintable():
        raise _reject(
            DCG_POLICY_MALFORMED_ALLOWLIST,
            f"DCG allowlist rule from {source} contains control characters.",
            source=source,
            rule=repr(rule),
        )
    anchors = sum(1 for char in rule if char.isalnum())
    if anchors < MIN_ALLOWLIST_ANCHOR_CHARS:
        raise _reject(
            DCG_POLICY_BROAD_ALLOWLIST,
            f"DCG allowlist rule {rule!r} from {source} has no literal anchor and "
            "would allow effectively any command.",
            source=source,
            rule=rule,
            min_anchor_chars=MIN_ALLOWLIST_ANCHOR_CHARS,
        )
    return rule


def _normalize_exception(raw: Any, *, source: str) -> FailOpenException:
    if not isinstance(raw, Mapping):
        raise _reject(
            DCG_POLICY_UNAUDITED_FAIL_OPEN,
            f"{source} set fail_closed = false without an audited exception record.",
            source=source,
        )
    values: dict[str, str] = {}
    for field in EXCEPTION_FIELDS:
        value = raw.get(field)
        if not isinstance(value, str) or not value.strip():
            raise _reject(
                DCG_POLICY_UNAUDITED_FAIL_OPEN,
                f"{source} fail_closed exception is missing a non-empty {field!r}.",
                source=source,
                required=list(EXCEPTION_FIELDS),
                missing=field,
            )
        values[field] = value.strip()
    unknown = sorted(set(raw) - set(EXCEPTION_FIELDS))
    if unknown:
        raise _reject(
            DCG_POLICY_MALFORMED_OVERLAY,
            f"{source} fail_closed exception carries unknown fields: {', '.join(unknown)}.",
            source=source,
            unknown=unknown,
        )
    try:
        date.fromisoformat(values["expires"])
    except ValueError as exc:
        raise _reject(
            DCG_POLICY_UNAUDITED_FAIL_OPEN,
            f"{source} fail_closed exception 'expires' must be an ISO date "
            f"(YYYY-MM-DD); got {values['expires']!r}.",
            source=source,
            expires=values["expires"],
        ) from exc
    return FailOpenException(**values)


# ---------------------------------------------------------------------------
# Policy construction
# ---------------------------------------------------------------------------


def build_policy(
    overlays: Iterable[Mapping[str, Any]] = (),
    *,
    base_packs: Sequence[str] = DEFAULT_PACKS,
    now: date | None = None,
) -> DcgPolicy:
    """Merge ``overlays`` onto the fail-closed defaults and validate the result.

    Precedence is deterministic and additive: the base packs come first in
    declared order, then each overlay's packs in overlay order, deduped
    first-wins. Overlays can only ADD -- there is no removal verb, so no client
    overlay can quietly shrink the guard. ``fail_closed`` is the one scalar an
    overlay may overwrite, and only downward with an audited exception attached.
    """
    packs: list[str] = []
    for pack in base_packs:
        normalized = _normalize_pack(pack, source="defaults")
        if normalized not in packs:
            packs.append(normalized)

    allowlist: list[str] = []
    fail_closed = True
    exception: FailOpenException | None = None

    for index, overlay in enumerate(overlays):
        if not isinstance(overlay, Mapping):
            raise _reject(
                DCG_POLICY_MALFORMED_OVERLAY,
                f"DCG overlay #{index} must be a mapping; got {type(overlay).__name__}.",
                overlay_index=index,
            )
        source = str(overlay.get("id") or f"overlay#{index}")
        unknown = sorted(set(overlay) - OVERLAY_KEYS)
        if unknown:
            raise _reject(
                DCG_POLICY_MALFORMED_OVERLAY,
                f"DCG overlay {source} carries unknown keys: {', '.join(unknown)}.",
                source=source,
                unknown=unknown,
                allowed=sorted(OVERLAY_KEYS),
            )

        raw_packs = overlay.get("packs") or []
        if isinstance(raw_packs, (str, bytes)) or not isinstance(raw_packs, Sequence):
            raise _reject(
                DCG_POLICY_MALFORMED_OVERLAY,
                f"DCG overlay {source} 'packs' must be a list of pack ids.",
                source=source,
            )
        for raw_pack in raw_packs:
            pack = _normalize_pack(raw_pack, source=source)
            if pack not in packs:
                packs.append(pack)

        raw_rules = overlay.get("allowlist") or []
        if isinstance(raw_rules, (str, bytes)) or not isinstance(raw_rules, Sequence):
            raise _reject(
                DCG_POLICY_MALFORMED_ALLOWLIST,
                f"DCG overlay {source} 'allowlist' must be a list of command rules.",
                source=source,
            )
        for raw_rule in raw_rules:
            rule = _normalize_allowlist_rule(raw_rule, source=source)
            if rule not in allowlist:
                allowlist.append(rule)

        if "fail_closed" in overlay:
            requested = overlay["fail_closed"]
            if not isinstance(requested, bool):
                raise _reject(
                    DCG_POLICY_MALFORMED_OVERLAY,
                    f"DCG overlay {source} 'fail_closed' must be a boolean.",
                    source=source,
                    fail_closed=repr(requested),
                )
            if requested:
                fail_closed = True
                exception = None
            else:
                exception = _normalize_exception(
                    overlay.get("fail_closed_exception"), source=source
                )
                fail_closed = False
        elif "fail_closed_exception" in overlay:
            raise _reject(
                DCG_POLICY_MALFORMED_OVERLAY,
                f"DCG overlay {source} declares a fail_closed exception without "
                "setting fail_closed = false.",
                source=source,
            )

    if len(allowlist) > MAX_ALLOWLIST_RULES:
        raise _reject(
            DCG_POLICY_BROAD_ALLOWLIST,
            f"DCG allowlist has {len(allowlist)} rules; the policy ceiling is "
            f"{MAX_ALLOWLIST_RULES}.",
            rule_count=len(allowlist),
            max_rules=MAX_ALLOWLIST_RULES,
        )

    if not fail_closed and exception is not None:
        today = now or date.today()
        if date.fromisoformat(exception.expires) < today:
            raise _reject(
                DCG_POLICY_EXPIRED_EXCEPTION,
                f"DCG fail_closed exception {exception.ticket} expired on "
                f"{exception.expires}; fail-closed is restored.",
                ticket=exception.ticket,
                expires=exception.expires,
                today=today.isoformat(),
            )

    return DcgPolicy(
        packs=tuple(packs),
        allowlist=tuple(allowlist),
        fail_closed=fail_closed,
        exception=exception,
    )


# ---------------------------------------------------------------------------
# Rendering
# ---------------------------------------------------------------------------


def _toml_string(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'


def _toml_array(values: Sequence[str]) -> str:
    return "[" + ", ".join(_toml_string(value) for value in values) + "]"


def render_policy(policy: DcgPolicy) -> str:
    """Render ``policy`` as ``.dcg.toml`` text. Deterministic, byte-for-byte."""
    lines: list[str] = [GENERATED_MARKER, POLICY_MARKER]
    if policy.fail_closed:
        lines.append("# fail_closed: unparseable hook input is DENIED, never allowed.")
    else:
        lines.append("# fail_closed: DISABLED under an audited exception.")
        for field in EXCEPTION_FIELDS:
            assert policy.exception is not None  # guaranteed by build_policy
            lines.append(f"#   {field}: {getattr(policy.exception, field)}")
    lines.extend(
        [
            "",
            "[general]",
            f"fail_closed = {'true' if policy.fail_closed else 'false'}",
            "",
            "[packs]",
            f"enabled = {_toml_array(policy.packs)}",
        ]
    )
    if policy.allowlist:
        lines.extend(
            [
                "",
                "[overrides]",
                f"allow = {_toml_array(policy.allowlist)}",
            ]
        )
    return "\n".join(lines) + "\n"


def render(
    overlays: Iterable[Mapping[str, Any]] = (),
    *,
    base_packs: Sequence[str] = DEFAULT_PACKS,
    now: date | None = None,
) -> str:
    """Build + render in one step (the common caller path)."""
    return render_policy(build_policy(overlays, base_packs=base_packs, now=now))


# ---------------------------------------------------------------------------
# Parse-back / upstream validation
# ---------------------------------------------------------------------------


def key_paths(document: Mapping[str, Any]) -> set[tuple[str, ...]]:
    """Flatten a parsed TOML document into ``(table, key)`` paths."""
    paths: set[tuple[str, ...]] = set()

    def walk(node: Mapping[str, Any], prefix: tuple[str, ...]) -> None:
        for key, value in node.items():
            path = prefix + (str(key),)
            if isinstance(value, Mapping):
                walk(value, path)
            else:
                paths.add(path)

    walk(document, ())
    return paths


def validate_rendered(text: str) -> DcgPolicy:
    """Parse rendered policy text back and re-assert every policy invariant.

    This is the upstream-syntax gate: the document must parse as TOML, must use
    ONLY the keys pinned in :data:`UPSTREAM_KEY_PATHS`, and must round-trip to a
    policy that ``build_policy`` would also accept.
    """
    if not text.startswith(GENERATED_MARKER):
        raise _reject(
            DCG_POLICY_UPSTREAM_MISMATCH,
            "Rendered DCG policy is missing the generated-ownership marker.",
        )
    try:
        document = tomllib.loads(text)
    except tomllib.TOMLDecodeError as exc:
        raise _reject(
            DCG_POLICY_UPSTREAM_MISMATCH,
            f"Rendered DCG policy is not valid TOML: {exc}",
        ) from exc

    unexpected = sorted(key_paths(document) - UPSTREAM_KEY_PATHS)
    if unexpected:
        raise _reject(
            DCG_POLICY_UPSTREAM_MISMATCH,
            "Rendered DCG policy uses keys outside the pinned upstream set: "
            + ", ".join(".".join(path) for path in unexpected),
            unexpected=[".".join(path) for path in unexpected],
            allowed=sorted(".".join(path) for path in UPSTREAM_KEY_PATHS),
        )

    general = document.get("general") or {}
    fail_closed = general.get("fail_closed")
    if not isinstance(fail_closed, bool):
        raise _reject(
            DCG_POLICY_UPSTREAM_MISMATCH,
            "Rendered DCG policy must declare a boolean [general] fail_closed.",
        )

    packs = (document.get("packs") or {}).get("enabled") or []
    allowlist = (document.get("overrides") or {}).get("allow") or []
    overlay: dict[str, Any] = {"id": "rendered", "packs": packs, "allowlist": allowlist}
    if not fail_closed:
        overlay["fail_closed"] = False
        overlay["fail_closed_exception"] = _exception_from_comments(text)
    # Re-running the builder proves the rendered artifact is itself admissible;
    # expiry is intentionally not re-checked here so an already-shipped config
    # validates the same way on any day.
    return build_policy([overlay], now=date.min)


def _exception_from_comments(text: str) -> dict[str, str]:
    """Recover the audited-exception record from the rendered header comments."""
    values: dict[str, str] = {}
    for line in text.splitlines():
        if not line.startswith("#   "):
            continue
        field, _, value = line[4:].partition(": ")
        if field in EXCEPTION_FIELDS and value:
            values[field] = value
    return values


def load_policy_file(path: Path) -> DcgPolicy:
    """Validate an on-disk ``.dcg.toml`` rendered by this module."""
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise _reject(
            DCG_POLICY_UPSTREAM_MISMATCH,
            f"Cannot read DCG policy at {path}: {exc}",
            path=str(path),
        ) from exc
    return validate_rendered(text)


# ---------------------------------------------------------------------------
# CLI
# ---------------------------------------------------------------------------


def _load_overlay_file(path: str) -> list[Mapping[str, Any]]:
    try:
        raw = json.loads(Path(path).read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        raise _reject(
            DCG_POLICY_MALFORMED_OVERLAY,
            f"Cannot read DCG overlay {path}: {exc}",
            path=path,
        ) from exc
    if isinstance(raw, Mapping):
        return [raw]
    if isinstance(raw, list):
        return list(raw)
    raise _reject(
        DCG_POLICY_MALFORMED_OVERLAY,
        f"DCG overlay {path} must be an object or a list of objects.",
        path=path,
    )


def _add_format(parser: argparse.ArgumentParser, *, default: Any) -> None:
    """``--format`` is accepted before OR after the subcommand.

    Subparsers use ``SUPPRESS`` as the default so an unspecified sub-level flag
    never clobbers a value already parsed at the top level.
    """
    parser.add_argument(
        "--format",
        choices=("text", "json"),
        default=default,
        help="Output format (json for agents/scripts).",
    )


def _build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(
        prog="python3 -m runtime_manager.dcg_policy",
        description="Render and validate the canonical Skillbox DCG policy.",
    )
    _add_format(parser, default="text")
    sub = parser.add_subparsers(dest="command", required=True)

    render_cmd = sub.add_parser("render", help="Render .dcg.toml from the policy.")
    render_cmd.add_argument("--output", help="Write the rendered policy to this path.")
    render_cmd.add_argument(
        "--overlay",
        action="append",
        default=[],
        metavar="PATH",
        help="JSON overlay file (object or list of objects). Repeatable, order-significant.",
    )
    _add_format(render_cmd, default=argparse.SUPPRESS)

    validate_cmd = sub.add_parser("validate", help="Validate a rendered .dcg.toml.")
    validate_cmd.add_argument(
        "--config",
        default=".dcg.toml",
        help="Path to the rendered policy (default: .dcg.toml).",
    )
    _add_format(validate_cmd, default=argparse.SUPPRESS)
    return parser


def _emit(payload: Mapping[str, Any], text_lines: Sequence[str], fmt: str) -> None:
    if fmt == "json":
        print(json.dumps(payload, indent=2, sort_keys=True))
        return
    for line in text_lines:
        print(line)


def main(argv: Sequence[str] | None = None) -> int:
    parser = _build_parser()
    args = parser.parse_args(list(argv) if argv is not None else None)
    try:
        if args.command == "render":
            overlays: list[Mapping[str, Any]] = []
            for path in args.overlay:
                overlays.extend(_load_overlay_file(path))
            policy = build_policy(overlays)
            content = render_policy(policy)
            validate_rendered(content)
            payload = policy.to_payload()
            if args.output:
                out = Path(args.output)
                if out.parent != Path(""):
                    out.parent.mkdir(parents=True, exist_ok=True)
                out.write_text(content, encoding="utf-8")
                payload["output"] = str(out)
                _emit(payload, [f"render-dcg-policy: {out}"], args.format)
            else:
                payload["content"] = content
                _emit(payload, [content.rstrip("\n")], args.format)
            return 0

        policy = load_policy_file(Path(args.config))
        payload = policy.to_payload()
        payload["config"] = args.config
        _emit(payload, [f"ok: {args.config}"], args.format)
        return 0
    except SkillboxError as exc:
        if args.format == "json":
            print(json.dumps(exc.to_payload(), indent=2, sort_keys=True))
        else:
            print(f"{exc.code}: {exc.message}", file=sys.stderr)
        return 1


__all__ = [
    "APPROVED_PACKS",
    "DCG_POLICY_BROAD_ALLOWLIST",
    "DCG_POLICY_ERROR_CODES",
    "DCG_POLICY_EXPIRED_EXCEPTION",
    "DCG_POLICY_MALFORMED_ALLOWLIST",
    "DCG_POLICY_MALFORMED_OVERLAY",
    "DCG_POLICY_MALFORMED_PACK",
    "DCG_POLICY_UNAUDITED_FAIL_OPEN",
    "DCG_POLICY_UNKNOWN_PACK",
    "DCG_POLICY_UPSTREAM_MISMATCH",
    "DEFAULT_PACKS",
    "DcgPolicy",
    "EXCEPTION_FIELDS",
    "FailOpenException",
    "GENERATED_MARKER",
    "MAX_ALLOWLIST_RULES",
    "OVERLAY_KEYS",
    "POLICY_MARKER",
    "POLICY_VERSION",
    "UPSTREAM_KEY_PATHS",
    "build_policy",
    "key_paths",
    "load_policy_file",
    "main",
    "render",
    "render_policy",
    "validate_rendered",
]


if __name__ == "__main__":  # pragma: no cover - CLI entry
    raise SystemExit(main())
