#!/usr/bin/env python3
from __future__ import annotations

# Back-compat re-export shim for the split runtime_manager._shared leaves.
# Keep this file declarative: implementation lives in _shared/*.py.
# ruff: noqa: F401
import argparse as argparse
import copy
import datetime
import fcntl
import hashlib
import json
import os
import re
import selectors as selectors
import shlex
import signal as signal
import shutil
import subprocess
import sys
import tempfile
import time
import urllib.error
import urllib.parse
import urllib.request
import zipfile
from dataclasses import asdict, dataclass
from pathlib import Path, PurePosixPath
from typing import Any, Callable
import types as _types

try:
    import yaml
except ModuleNotFoundError:
    yaml = None

PACKAGE_DIR = Path(__file__).resolve().parent
SCRIPT_DIR = PACKAGE_DIR.parent
DEFAULT_ROOT_DIR = SCRIPT_DIR.parent.resolve()
SCRIPTS_DIR = DEFAULT_ROOT_DIR / "scripts"

if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

if __package__:
    from .errors import DEPRECATION_MARKER  # noqa: E402
else:  # loaded standalone (SourceFileLoader) without a package
    if str(PACKAGE_DIR) not in sys.path:
        sys.path.insert(0, str(PACKAGE_DIR))
    from errors import DEPRECATION_MARKER  # type: ignore[no-redef]  # noqa: E402

from lib.runtime_model import (  # noqa: E402
    LOOPBACK_BIND_HOSTS as LOOPBACK_BIND_HOSTS,
    PERSISTENCE_ERROR_CODES,
    PersistenceContractError,
    RUNTIME_ID_INVALID,
    RUNTIME_ID_PATTERN,
    RUNTIME_ID_PATTERN_TEXT,
    RuntimeIdValidationError as RuntimeIdValidationError,
    WILDCARD_BIND_HOSTS as WILDCARD_BIND_HOSTS,
    build_runtime_model,
    classify_bind_scope as classify_bind_scope,
    client_config_host_dir,
    client_config_runtime_dir,
    client_configs_host_root,
    compile_persistence_summary,
    extract_command_port as extract_command_port,
    extract_host_port as extract_host_port,
    host_path_to_absolute_path,
    load_yaml,
    load_runtime_env,
    runtime_manifest_path,
    runtime_path_to_host_path as runtime_path_to_host_path,
    storage_binding_by_id,
    validate_runtime_id as validate_runtime_id,
)
from lib.redaction import REDACTION_MARKER as REDACTION_MARKER  # noqa: E402
from lib.redaction import SECRET_KEY_PATTERN as SECRET_KEY_PATTERN  # noqa: E402
from lib.redaction import is_secret_key as is_secret_key  # noqa: E402
from lib.redaction import redact_text as redact_text  # noqa: E402
from lib.redaction import redact_value as redact_value  # noqa: E402

if __package__:
    from ._shared import digest as _shared_digest
    from ._shared import textutil as _shared_textutil
    from ._shared import proc as _shared_proc
    from ._shared import errors as _shared_errors
    from ._shared import next_actions as _shared_next_actions
    from ._shared import events as _shared_events
    from ._shared import fs as _shared_fs
    from ._shared import envio as _shared_envio
    from ._shared import session as _shared_session
    from ._shared import worker as _shared_worker
    from ._shared import client_scaffold as _shared_client_scaffold
    from ._shared import skill_sync as _shared_skill_sync
    from ._shared import client as _shared_client
else:
    if str(SCRIPT_DIR) not in sys.path:
        sys.path.insert(0, str(SCRIPT_DIR))
    from runtime_manager._shared import digest as _shared_digest
    from runtime_manager._shared import textutil as _shared_textutil
    from runtime_manager._shared import proc as _shared_proc
    from runtime_manager._shared import errors as _shared_errors
    from runtime_manager._shared import next_actions as _shared_next_actions
    from runtime_manager._shared import events as _shared_events
    from runtime_manager._shared import fs as _shared_fs
    from runtime_manager._shared import envio as _shared_envio
    from runtime_manager._shared import session as _shared_session
    from runtime_manager._shared import worker as _shared_worker
    from runtime_manager._shared import client_scaffold as _shared_client_scaffold
    from runtime_manager._shared import skill_sync as _shared_skill_sync
    from runtime_manager._shared import client as _shared_client

if __package__:
    from ._shared.digest import (
        SHA256_HEX_PATTERN,
        normalize_sha256,
        digest_bytes,
        file_sha256,
        tree_hash,
        directory_tree_sha256,
        read_manifest_skills,
        bundle_members,
        bundle_metadata,
    )
    from ._shared.textutil import (
        CLIENT_ID_PATTERN,
        human_bytes,
        titleize_client_id,
        validate_client_id,
        parse_key_value_assignments,
        resolve_known_placeholders,
        split_csv_values,
        find_duplicates,
        unique_string_field_values,
        json_or_none,
        walk_values,
        directory_file_entries,
        normalize_bundle_rel_path,
    )
    from ._shared.proc import (
        run_command,
    )
    from ._shared.errors import (
        EXIT_OK,
        EXIT_ERROR,
        EXIT_DRIFT,
        EXIT_NEEDS_INPUT,
        CheckResult,
        structured_error,
        _classify_persistence_error,
        _classify_message_pattern,
        _COMMAND_FALLBACK_NEXT_ACTIONS,
        classify_error,
    )
    from ._shared.next_actions import (
        next_actions_for_doctor,
        is_elevated_pressure_level,
        pressure_advisory_warning_messages,
        next_actions_for_status,
        next_actions_for_sync,
        next_actions_for_up,
        next_actions_for_down,
        next_actions_for_bootstrap,
        next_actions_for_context,
        next_actions_for_private_init,
        next_actions_for_client_init,
        next_actions_for_focus,
        next_actions_for_session_start,
        next_actions_for_session_status,
        next_actions_for_session_event,
        next_actions_for_session_end,
        next_actions_for_session_resume,
        format_profile_args,
        next_actions_for_acceptance_success,
        next_actions_for_acceptance_mcp_failure,
        next_actions_for_client_project,
        next_actions_for_client_publish,
        next_actions_for_client_diff,
        next_actions_for_client_open,
        next_actions_for_first_box,
    )
    from ._shared.events import (
        RUNTIME_LOG_REL,
        MCP_EVENT_CONTEXT_ENV,
        current_mcp_event_context,
        merge_runtime_event_detail,
        log_runtime_event,
    )
    from ._shared.fs import (
        PACKAGE_DIR,
        SCRIPT_DIR,
        DEFAULT_ROOT_DIR,
        SCRIPTS_DIR,
        CONTEXT_CLAUDE_REL,
        CONTEXT_CODEX_REL,
        CONTEXT_SYMLINK_TARGET,
        repo_rel,
        resolve_context_dir,
        context_output_paths,
        client_overlay_location,
        client_context_location,
        _append_jsonl,
        resolve_root_dir,
        _ATOMICITY_KILL_AT_ENV,
        _ATOMICITY_COUNTER_ENV,
        _atomicity_checkpoint_count,
        _atomicity_checkpoint,
        _fsync_directory,
        atomic_write_bytes,
        atomic_write_text,
        write_text_file,
        DEFAULT_STATE_LOCK_TIMEOUT_SECONDS,
        _STATE_LOCK_POLL_INTERVAL_SECONDS,
        _STATE_LOCK_WAIT_WARN_SECONDS,
        _flock_unsupported_warned,
        StateLockTimeout,
        _state_lock_age_seconds,
        _warn_flock_unsupported,
        read_json_tolerant,
        _atomic_write_json_serialized,
        atomic_write_json,
        locked_json_update,
        normalize_host_rel_path,
        ensure_directory,
        artifact_source_configured,
        validate_url_download_source,
        remove_path,
        _recover_interrupted_tree_swap,
        atomic_replace_tree,
        copy_tree_atomic,
        load_json_file,
        write_json_file,
        emit_json,
    )
    from ._shared.envio import (
        VALID_REPO_SOURCE_KINDS,
        VALID_SYNC_MODES,
        VALID_ARTIFACT_SOURCE_KINDS,
        VALID_ARTIFACT_SYNC_MODES,
        VALID_ENV_FILE_SOURCE_KINDS,
        VALID_ENV_FILE_SYNC_MODES,
        VALID_HEALTHCHECK_TYPES,
        VALID_CHECK_TYPES,
        VALID_TASK_SUCCESS_TYPES,
        LOCKFILE_VERSION,
        DEFAULT_SERVICE_START_WAIT_SECONDS,
        DEFAULT_SERVICE_STOP_WAIT_SECONDS,
        DEFAULT_LOG_TAIL_LINES,
        DEFAULT_TASK_TIMEOUT_SECONDS,
        PATH_LIKE_ENV_KEYS,
        upsert_env_file_values,
        require_yaml,
        render_yaml_document,
    )
    from ._shared.session import (
        SESSION_SCHEMA_VERSION,
        SESSION_ACTIVE_STATUS,
        SESSION_TERMINAL_STATUSES,
        DEFAULT_EVENT_FEED_LIMIT,
        DEFAULT_EVENT_FEED_POLL_INTERVAL_SECONDS,
        _session_now,
        _session_subject,
        _normalize_session_event_type,
        _generate_session_id,
        _ensure_client_exists,
        resolve_client_log_root,
        resolve_client_session_root,
        session_paths,
        _write_session_handoff,
        _read_session_meta,
        _read_session_events,
        _session_payload,
        list_client_sessions,
        read_client_session,
        _persist_session_event,
        start_client_session,
        append_client_session_event,
        end_client_session,
        resume_client_session,
        session_status_payload,
        _runtime_log_timestamp,
        parse_runtime_log_line,
        _event_matches_scope,
        read_runtime_log_events,
        _session_event_roots,
        _durable_session_event_paths,
        _load_durable_session_meta,
        _iter_jsonl_dicts,
        _durable_session_event_payload,
        read_durable_session_events,
        event_feed_payload,
    )
    from ._shared.worker import (
        WORKER_RUN_SCHEMA_VERSION,
        WORKER_TASK_CLASSES,
        WORKER_RUNTIME_IDS,
        WORKER_WRITE_SCOPES,
        WORKER_MEMORY_SCOPES,
        WORKER_RUN_STATES,
        WORKER_ERROR_CODES,
        WORKER_CONTEXT_UNRESOLVED,
        WORKER_RUNTIME_UNKNOWN,
        WORKER_POLICY_BLOCKED,
        WORKER_LAUNCH_FAILED,
        WORKER_RUN_NOT_FOUND,
        WORKER_RESULT_NOT_READY,
        WORKER_LEARNING_REVIEW_REQUIRED,
        WORKER_WRITEBACK_REJECTED,
        WORKER_DEFAULT_RUNTIME_ID,
        WORKER_DEFAULT_WRITE_SCOPE,
        WORKER_DEFAULT_MEMORY_SCOPE,
        WORKER_DEFAULT_ARTIFACT_POLICY,
        WORKER_DEFAULT_LAUNCH_TIMEOUT_SECONDS,
        WORKER_LAUNCH_SETTLE_SECONDS,
        _WORKER_ACTIVE_PROCESSES,
        WORKER_RUN_ID_PATTERN,
        WORKER_TERMINAL_STATES,
        WORKER_BROKER_MCP_SURFACES,
        WorkerRuntimeError,
        WorkerTaskSpec,
        WorkerRun,
        worker_runtime_error_payload,
        _worker_now,
        _generate_worker_run_id,
        _normalize_worker_run_id,
        _normalize_worker_choice,
        _normalize_worker_runtime,
        _normalize_worker_client_id,
        worker_runs_root,
        worker_run_paths,
        _iter_worker_run_paths,
        read_worker_run,
        _worker_client_index,
        _worker_safe_path,
        _worker_client_match_paths,
        _worker_path_contains,
        _worker_client_id_from_cwd,
        _worker_repo_id,
        _worker_resolved_context,
        _resolve_worker_context,
        _ensure_worker_write_scope_allowed,
        _worker_hermes_command,
        _worker_effective_cwd,
        _worker_launch_paths,
        _worker_launch_env,
        _worker_launch_timeout_seconds,
        _worker_result_payload,
        _worker_summary_artifact,
        _worker_apply_terminal_result,
        _worker_mark_launching,
        _worker_mark_running,
        _worker_mark_launch_failed,
        _worker_loaded_result,
        _worker_apply_terminal_from_launch_paths,
        _worker_launch_pid,
        _worker_reap_active_process,
        _worker_pid_running,
        _worker_stderr_tail,
        _reconcile_worker_payload,
        _persist_worker_payload,
        _launch_worker_if_ready,
        create_worker_run,
        worker_status_payload,
        worker_artifacts_payload,
        _worker_payload_state,
        _worker_learning_review_required,
        _find_worker_learning_proposal,
        _worker_promotion_response,
        _worker_proposal_status,
        _reject_pending_worker_proposal,
        _normalize_worker_promotion_mode,
        _worker_proposal_target_matches,
        _ensure_worker_proposal_promotable,
        _mark_worker_proposal_promoted,
        promote_worker_learning,
    )
    from ._shared.client_scaffold import (
        CLIENT_PLANNING_SKILL_TEMPLATE_REL,
        CLIENT_SKILL_BUILDER_TEMPLATE_REL,
        BLUEPRINT_VARIABLE_PATTERN,
        SCAFFOLD_PLACEHOLDER_PATTERN,
        GLOBAL_HOME_ROOT_ENV,
        GLOBAL_HOME_SURFACES,
        managed_home_install_targets,
        HARDENED_SHARED_DEFAULT_SKILLS,
        HARDENED_CLIENT_PLANNING_SKILLS,
        HARDENED_CLIENT_SKILL_BUILDER_SKILLS,
        HARDENED_CLIENT_HYBRID_SKILLS,
        HARDENED_CLIENT_PLAN_PATHS,
        HARDENED_CLIENT_SKILL_BUILDER_CONTEXT,
        client_blueprint_dir,
        normalize_client_connector_entries,
        scaffold_connector_entries,
        list_client_blueprints,
        resolve_client_blueprint_path,
        load_client_blueprint,
        base_client_overlay,
        render_client_plan_index,
        client_plan_seed_files,
        client_planning_skill_template_root,
        render_skill_builder_index,
        render_skill_builder_extraction_rule,
        client_skill_builder_seed_files,
        client_skill_builder_template_root,
        client_scaffold_pack,
        client_scaffold_pack_required_skills,
        client_scaffold_pack_skill_templates,
        client_scaffold_shared_skills_dir,
        client_scaffold_local_skills_dir,
        client_scaffold_skill_repo_entries,
        render_client_scaffold_skill_repos,
        client_scaffold_keep_files,
        client_scaffold_seed_files,
        sync_client_scaffold_seed_files,
        ensure_client_scaffold_skill_sources,
        default_client_scaffold_files,
        merge_client_overlay,
        build_blueprinted_client_scaffold_files,
        scaffold_client_overlay,
    )
    from ._shared.skill_sync import (
        VALID_SKILL_SYNC_MODES,
        SKILL_REPOS_LOCKFILE_VERSION,
        SKILL_REPOS_CONFIG_VERSION,
        SHARED_SKILL_ASSET_DIR,
        DEFAULT_SKILLIGNORE_PATTERNS,
        CLONE_DIR_ROOT_REL,
        load_skill_repos_config,
        clone_dir_name,
        _load_skillignore,
        _matches_skillignore,
        filtered_copy_skill,
        _resolve_skill_dirs,
        _checkout_skill_repo_ref,
        _current_skill_repo_commit,
        _pull_skill_repo_branch,
        _fetch_existing_skill_repo,
        _clone_new_skill_repo,
        _clone_or_fetch_repo,
        _resolve_skill_repo_entry_source,
        _install_skill_to_targets,
        _shared_skill_asset_source,
        _install_shared_skill_asset_to_targets,
        _host_skill_mirror_root,
        _mirror_installed_skill_to_host_home,
        _symlink_points_inside,
        _reconcile_host_skill_mirrors,
        _skill_repo_lock_skill_names,
        _build_lock_skill_entry,
        _persist_skill_repo_lockfile,
        sync_skill_repo_sets,
    )
    from ._shared.client import (
        CLIENT_PROJECTS_REL,
        CLIENT_OPEN_ROOT_REL,
        CLIENT_PROJECTION_VERSION,
        CLIENT_PROJECT_RUNTIME_MODEL_REL,
        CLIENT_PROJECTION_METADATA_REL,
        CLIENT_PUBLISH_VERSION,
        CLIENT_ACCEPTANCE_VERSION,
        CLIENT_DEPLOY_VERSION,
        CLIENT_PUBLISH_ROOT_REL,
        CLIENT_PUBLISH_CURRENT_REL,
        CLIENT_PUBLISH_METADATA_REL,
        CLIENT_ACCEPTANCE_METADATA_REL,
        CLIENT_DEPLOY_METADATA_REL,
        CLIENT_DEPLOY_ARTIFACTS_REL,
        DEFAULT_PRIVATE_REPO_REL,
        CLIENT_OVERLAY_PROJECTION_ROOT_FILES,
        CLIENT_OVERLAY_PROJECTION_DIRS,
        resolve_client_projection_output_dir,
        resolve_client_open_output_dir,
        runtime_path_to_projection_rel_path,
        prepare_client_projection_output_dir,
        add_projection_source_file,
        add_projection_source_tree,
        add_projection_text_file,
        sanitize_projection_env,
        sanitize_projection_source,
        sanitize_projection_value,
        build_projected_runtime_manifest,
        _add_projection_runtime_manifest,
        _add_projection_optional_root_files,
        _add_overlay_projection_files,
        _add_skill_repo_set_projection_files,
        _add_packaged_skillset_projection_files,
        _add_projection_skillset_files,
        _projection_runtime_model_payload,
        collect_client_projection_files,
        materialize_client_projection,
        project_client_bundle,
        resolve_optional_host_dir,
        inferred_private_target_dir,
        ensure_git_repo,
        migrate_client_overlay_tree,
        migrate_client_subtree,
        ensure_client_overlay_skillset_shape,
        ensure_client_overlay_scaffold_shape,
        ensure_client_overlay_context_shape,
        normalize_client_overlay_shape,
        init_private_repo,
        resolve_client_publish_target_dir,
        resolve_client_publish_bundle_dir,
        git_head_commit,
        git_dirty_paths,
        load_client_projection_bundle,
        CLIENT_RUNTIME_DIFF_SECTIONS,
        CLIENT_PUBLISH_METADATA_COMPARE_FIELDS,
        CLIENT_ACCEPTANCE_MATCH_FIELDS,
    )
else:
    from runtime_manager._shared.digest import (
        SHA256_HEX_PATTERN,
        normalize_sha256,
        digest_bytes,
        file_sha256,
        tree_hash,
        directory_tree_sha256,
        read_manifest_skills,
        bundle_members,
        bundle_metadata,
    )
    from runtime_manager._shared.textutil import (
        CLIENT_ID_PATTERN,
        human_bytes,
        titleize_client_id,
        validate_client_id,
        parse_key_value_assignments,
        resolve_known_placeholders,
        split_csv_values,
        find_duplicates,
        unique_string_field_values,
        json_or_none,
        walk_values,
        directory_file_entries,
        normalize_bundle_rel_path,
    )
    from runtime_manager._shared.proc import (
        run_command,
    )
    from runtime_manager._shared.errors import (
        EXIT_OK,
        EXIT_ERROR,
        EXIT_DRIFT,
        EXIT_NEEDS_INPUT,
        CheckResult,
        structured_error,
        _classify_persistence_error,
        _classify_message_pattern,
        _COMMAND_FALLBACK_NEXT_ACTIONS,
        classify_error,
    )
    from runtime_manager._shared.next_actions import (
        next_actions_for_doctor,
        is_elevated_pressure_level,
        pressure_advisory_warning_messages,
        next_actions_for_status,
        next_actions_for_sync,
        next_actions_for_up,
        next_actions_for_down,
        next_actions_for_bootstrap,
        next_actions_for_context,
        next_actions_for_private_init,
        next_actions_for_client_init,
        next_actions_for_focus,
        next_actions_for_session_start,
        next_actions_for_session_status,
        next_actions_for_session_event,
        next_actions_for_session_end,
        next_actions_for_session_resume,
        format_profile_args,
        next_actions_for_acceptance_success,
        next_actions_for_acceptance_mcp_failure,
        next_actions_for_client_project,
        next_actions_for_client_publish,
        next_actions_for_client_diff,
        next_actions_for_client_open,
        next_actions_for_first_box,
    )
    from runtime_manager._shared.events import (
        RUNTIME_LOG_REL,
        MCP_EVENT_CONTEXT_ENV,
        current_mcp_event_context,
        merge_runtime_event_detail,
        log_runtime_event,
    )
    from runtime_manager._shared.fs import (
        PACKAGE_DIR,
        SCRIPT_DIR,
        DEFAULT_ROOT_DIR,
        SCRIPTS_DIR,
        CONTEXT_CLAUDE_REL,
        CONTEXT_CODEX_REL,
        CONTEXT_SYMLINK_TARGET,
        repo_rel,
        resolve_context_dir,
        context_output_paths,
        client_overlay_location,
        client_context_location,
        _append_jsonl,
        resolve_root_dir,
        _ATOMICITY_KILL_AT_ENV,
        _ATOMICITY_COUNTER_ENV,
        _atomicity_checkpoint_count,
        _atomicity_checkpoint,
        _fsync_directory,
        atomic_write_bytes,
        atomic_write_text,
        write_text_file,
        DEFAULT_STATE_LOCK_TIMEOUT_SECONDS,
        _STATE_LOCK_POLL_INTERVAL_SECONDS,
        _STATE_LOCK_WAIT_WARN_SECONDS,
        _flock_unsupported_warned,
        StateLockTimeout,
        _state_lock_age_seconds,
        _warn_flock_unsupported,
        read_json_tolerant,
        _atomic_write_json_serialized,
        atomic_write_json,
        locked_json_update,
        normalize_host_rel_path,
        ensure_directory,
        artifact_source_configured,
        validate_url_download_source,
        remove_path,
        _recover_interrupted_tree_swap,
        atomic_replace_tree,
        copy_tree_atomic,
        load_json_file,
        write_json_file,
        emit_json,
    )
    from runtime_manager._shared.envio import (
        VALID_REPO_SOURCE_KINDS,
        VALID_SYNC_MODES,
        VALID_ARTIFACT_SOURCE_KINDS,
        VALID_ARTIFACT_SYNC_MODES,
        VALID_ENV_FILE_SOURCE_KINDS,
        VALID_ENV_FILE_SYNC_MODES,
        VALID_HEALTHCHECK_TYPES,
        VALID_CHECK_TYPES,
        VALID_TASK_SUCCESS_TYPES,
        LOCKFILE_VERSION,
        DEFAULT_SERVICE_START_WAIT_SECONDS,
        DEFAULT_SERVICE_STOP_WAIT_SECONDS,
        DEFAULT_LOG_TAIL_LINES,
        DEFAULT_TASK_TIMEOUT_SECONDS,
        PATH_LIKE_ENV_KEYS,
        upsert_env_file_values,
        require_yaml,
        render_yaml_document,
    )
    from runtime_manager._shared.session import (
        SESSION_SCHEMA_VERSION,
        SESSION_ACTIVE_STATUS,
        SESSION_TERMINAL_STATUSES,
        DEFAULT_EVENT_FEED_LIMIT,
        DEFAULT_EVENT_FEED_POLL_INTERVAL_SECONDS,
        _session_now,
        _session_subject,
        _normalize_session_event_type,
        _generate_session_id,
        _ensure_client_exists,
        resolve_client_log_root,
        resolve_client_session_root,
        session_paths,
        _write_session_handoff,
        _read_session_meta,
        _read_session_events,
        _session_payload,
        list_client_sessions,
        read_client_session,
        _persist_session_event,
        start_client_session,
        append_client_session_event,
        end_client_session,
        resume_client_session,
        session_status_payload,
        _runtime_log_timestamp,
        parse_runtime_log_line,
        _event_matches_scope,
        read_runtime_log_events,
        _session_event_roots,
        _durable_session_event_paths,
        _load_durable_session_meta,
        _iter_jsonl_dicts,
        _durable_session_event_payload,
        read_durable_session_events,
        event_feed_payload,
    )
    from runtime_manager._shared.worker import (
        WORKER_RUN_SCHEMA_VERSION,
        WORKER_TASK_CLASSES,
        WORKER_RUNTIME_IDS,
        WORKER_WRITE_SCOPES,
        WORKER_MEMORY_SCOPES,
        WORKER_RUN_STATES,
        WORKER_ERROR_CODES,
        WORKER_CONTEXT_UNRESOLVED,
        WORKER_RUNTIME_UNKNOWN,
        WORKER_POLICY_BLOCKED,
        WORKER_LAUNCH_FAILED,
        WORKER_RUN_NOT_FOUND,
        WORKER_RESULT_NOT_READY,
        WORKER_LEARNING_REVIEW_REQUIRED,
        WORKER_WRITEBACK_REJECTED,
        WORKER_DEFAULT_RUNTIME_ID,
        WORKER_DEFAULT_WRITE_SCOPE,
        WORKER_DEFAULT_MEMORY_SCOPE,
        WORKER_DEFAULT_ARTIFACT_POLICY,
        WORKER_DEFAULT_LAUNCH_TIMEOUT_SECONDS,
        WORKER_LAUNCH_SETTLE_SECONDS,
        _WORKER_ACTIVE_PROCESSES,
        WORKER_RUN_ID_PATTERN,
        WORKER_TERMINAL_STATES,
        WORKER_BROKER_MCP_SURFACES,
        WorkerRuntimeError,
        WorkerTaskSpec,
        WorkerRun,
        worker_runtime_error_payload,
        _worker_now,
        _generate_worker_run_id,
        _normalize_worker_run_id,
        _normalize_worker_choice,
        _normalize_worker_runtime,
        _normalize_worker_client_id,
        worker_runs_root,
        worker_run_paths,
        _iter_worker_run_paths,
        read_worker_run,
        _worker_client_index,
        _worker_safe_path,
        _worker_client_match_paths,
        _worker_path_contains,
        _worker_client_id_from_cwd,
        _worker_repo_id,
        _worker_resolved_context,
        _resolve_worker_context,
        _ensure_worker_write_scope_allowed,
        _worker_hermes_command,
        _worker_effective_cwd,
        _worker_launch_paths,
        _worker_launch_env,
        _worker_launch_timeout_seconds,
        _worker_result_payload,
        _worker_summary_artifact,
        _worker_apply_terminal_result,
        _worker_mark_launching,
        _worker_mark_running,
        _worker_mark_launch_failed,
        _worker_loaded_result,
        _worker_apply_terminal_from_launch_paths,
        _worker_launch_pid,
        _worker_reap_active_process,
        _worker_pid_running,
        _worker_stderr_tail,
        _reconcile_worker_payload,
        _persist_worker_payload,
        _launch_worker_if_ready,
        create_worker_run,
        worker_status_payload,
        worker_artifacts_payload,
        _worker_payload_state,
        _worker_learning_review_required,
        _find_worker_learning_proposal,
        _worker_promotion_response,
        _worker_proposal_status,
        _reject_pending_worker_proposal,
        _normalize_worker_promotion_mode,
        _worker_proposal_target_matches,
        _ensure_worker_proposal_promotable,
        _mark_worker_proposal_promoted,
        promote_worker_learning,
    )
    from runtime_manager._shared.client_scaffold import (
        CLIENT_PLANNING_SKILL_TEMPLATE_REL,
        CLIENT_SKILL_BUILDER_TEMPLATE_REL,
        BLUEPRINT_VARIABLE_PATTERN,
        SCAFFOLD_PLACEHOLDER_PATTERN,
        GLOBAL_HOME_ROOT_ENV,
        GLOBAL_HOME_SURFACES,
        managed_home_install_targets,
        HARDENED_SHARED_DEFAULT_SKILLS,
        HARDENED_CLIENT_PLANNING_SKILLS,
        HARDENED_CLIENT_SKILL_BUILDER_SKILLS,
        HARDENED_CLIENT_HYBRID_SKILLS,
        HARDENED_CLIENT_PLAN_PATHS,
        HARDENED_CLIENT_SKILL_BUILDER_CONTEXT,
        client_blueprint_dir,
        normalize_client_connector_entries,
        scaffold_connector_entries,
        list_client_blueprints,
        resolve_client_blueprint_path,
        load_client_blueprint,
        base_client_overlay,
        render_client_plan_index,
        client_plan_seed_files,
        client_planning_skill_template_root,
        render_skill_builder_index,
        render_skill_builder_extraction_rule,
        client_skill_builder_seed_files,
        client_skill_builder_template_root,
        client_scaffold_pack,
        client_scaffold_pack_required_skills,
        client_scaffold_pack_skill_templates,
        client_scaffold_shared_skills_dir,
        client_scaffold_local_skills_dir,
        client_scaffold_skill_repo_entries,
        render_client_scaffold_skill_repos,
        client_scaffold_keep_files,
        client_scaffold_seed_files,
        sync_client_scaffold_seed_files,
        ensure_client_scaffold_skill_sources,
        default_client_scaffold_files,
        merge_client_overlay,
        build_blueprinted_client_scaffold_files,
        scaffold_client_overlay,
    )
    from runtime_manager._shared.skill_sync import (
        VALID_SKILL_SYNC_MODES,
        SKILL_REPOS_LOCKFILE_VERSION,
        SKILL_REPOS_CONFIG_VERSION,
        SHARED_SKILL_ASSET_DIR,
        DEFAULT_SKILLIGNORE_PATTERNS,
        CLONE_DIR_ROOT_REL,
        load_skill_repos_config,
        clone_dir_name,
        _load_skillignore,
        _matches_skillignore,
        filtered_copy_skill,
        _resolve_skill_dirs,
        _checkout_skill_repo_ref,
        _current_skill_repo_commit,
        _pull_skill_repo_branch,
        _fetch_existing_skill_repo,
        _clone_new_skill_repo,
        _clone_or_fetch_repo,
        _resolve_skill_repo_entry_source,
        _install_skill_to_targets,
        _shared_skill_asset_source,
        _install_shared_skill_asset_to_targets,
        _host_skill_mirror_root,
        _mirror_installed_skill_to_host_home,
        _symlink_points_inside,
        _reconcile_host_skill_mirrors,
        _skill_repo_lock_skill_names,
        _build_lock_skill_entry,
        _persist_skill_repo_lockfile,
        sync_skill_repo_sets,
    )
    from runtime_manager._shared.client import (
        CLIENT_PROJECTS_REL,
        CLIENT_OPEN_ROOT_REL,
        CLIENT_PROJECTION_VERSION,
        CLIENT_PROJECT_RUNTIME_MODEL_REL,
        CLIENT_PROJECTION_METADATA_REL,
        CLIENT_PUBLISH_VERSION,
        CLIENT_ACCEPTANCE_VERSION,
        CLIENT_DEPLOY_VERSION,
        CLIENT_PUBLISH_ROOT_REL,
        CLIENT_PUBLISH_CURRENT_REL,
        CLIENT_PUBLISH_METADATA_REL,
        CLIENT_ACCEPTANCE_METADATA_REL,
        CLIENT_DEPLOY_METADATA_REL,
        CLIENT_DEPLOY_ARTIFACTS_REL,
        DEFAULT_PRIVATE_REPO_REL,
        CLIENT_OVERLAY_PROJECTION_ROOT_FILES,
        CLIENT_OVERLAY_PROJECTION_DIRS,
        resolve_client_projection_output_dir,
        resolve_client_open_output_dir,
        runtime_path_to_projection_rel_path,
        prepare_client_projection_output_dir,
        add_projection_source_file,
        add_projection_source_tree,
        add_projection_text_file,
        sanitize_projection_env,
        sanitize_projection_source,
        sanitize_projection_value,
        build_projected_runtime_manifest,
        _add_projection_runtime_manifest,
        _add_projection_optional_root_files,
        _add_overlay_projection_files,
        _add_skill_repo_set_projection_files,
        _add_packaged_skillset_projection_files,
        _add_projection_skillset_files,
        _projection_runtime_model_payload,
        collect_client_projection_files,
        materialize_client_projection,
        project_client_bundle,
        resolve_optional_host_dir,
        inferred_private_target_dir,
        ensure_git_repo,
        migrate_client_overlay_tree,
        migrate_client_subtree,
        ensure_client_overlay_skillset_shape,
        ensure_client_overlay_scaffold_shape,
        ensure_client_overlay_context_shape,
        normalize_client_overlay_shape,
        init_private_repo,
        resolve_client_publish_target_dir,
        resolve_client_publish_bundle_dir,
        git_head_commit,
        git_dirty_paths,
        load_client_projection_bundle,
        CLIENT_RUNTIME_DIFF_SECTIONS,
        CLIENT_PUBLISH_METADATA_COMPARE_FIELDS,
        CLIENT_ACCEPTANCE_MATCH_FIELDS,
    )

_SHARED_LEAF_MODULES = (
    _shared_digest,
    _shared_textutil,
    _shared_proc,
    _shared_errors,
    _shared_next_actions,
    _shared_events,
    _shared_fs,
    _shared_envio,
    _shared_session,
    _shared_worker,
    _shared_client_scaffold,
    _shared_skill_sync,
    _shared_client,
)

_SHARED_DIR_BASELINE = (
    'Any', 'BLUEPRINT_VARIABLE_PATTERN', 'CLIENT_ACCEPTANCE_MATCH_FIELDS', 'CLIENT_ACCEPTANCE_METADATA_REL',
    'CLIENT_ACCEPTANCE_VERSION', 'CLIENT_DEPLOY_ARTIFACTS_REL', 'CLIENT_DEPLOY_METADATA_REL', 'CLIENT_DEPLOY_VERSION',
    'CLIENT_ID_PATTERN', 'CLIENT_OPEN_ROOT_REL', 'CLIENT_OVERLAY_PROJECTION_DIRS', 'CLIENT_OVERLAY_PROJECTION_ROOT_FILES',
    'CLIENT_PLANNING_SKILL_TEMPLATE_REL', 'CLIENT_PROJECTION_METADATA_REL', 'CLIENT_PROJECTION_VERSION', 'CLIENT_PROJECTS_REL',
    'CLIENT_PROJECT_RUNTIME_MODEL_REL', 'CLIENT_PUBLISH_CURRENT_REL', 'CLIENT_PUBLISH_METADATA_COMPARE_FIELDS', 'CLIENT_PUBLISH_METADATA_REL',
    'CLIENT_PUBLISH_ROOT_REL', 'CLIENT_PUBLISH_VERSION', 'CLIENT_RUNTIME_DIFF_SECTIONS', 'CLIENT_SKILL_BUILDER_TEMPLATE_REL',
    'CLONE_DIR_ROOT_REL', 'CONTEXT_CLAUDE_REL', 'CONTEXT_CODEX_REL', 'CONTEXT_SYMLINK_TARGET',
    'Callable', 'CheckResult', 'DEFAULT_EVENT_FEED_LIMIT', 'DEFAULT_EVENT_FEED_POLL_INTERVAL_SECONDS',
    'DEFAULT_LOG_TAIL_LINES', 'DEFAULT_PRIVATE_REPO_REL', 'DEFAULT_ROOT_DIR', 'DEFAULT_SERVICE_START_WAIT_SECONDS',
    'DEFAULT_SERVICE_STOP_WAIT_SECONDS', 'DEFAULT_SKILLIGNORE_PATTERNS', 'DEFAULT_STATE_LOCK_TIMEOUT_SECONDS', 'DEFAULT_TASK_TIMEOUT_SECONDS',
    'DEPRECATION_MARKER', 'EXIT_DRIFT', 'EXIT_ERROR', 'EXIT_NEEDS_INPUT',
    'EXIT_OK', 'GLOBAL_HOME_ROOT_ENV', 'GLOBAL_HOME_SURFACES', 'HARDENED_CLIENT_HYBRID_SKILLS',
    'HARDENED_CLIENT_PLANNING_SKILLS', 'HARDENED_CLIENT_PLAN_PATHS', 'HARDENED_CLIENT_SKILL_BUILDER_CONTEXT', 'HARDENED_CLIENT_SKILL_BUILDER_SKILLS',
    'HARDENED_SHARED_DEFAULT_SKILLS', 'LOCKFILE_VERSION', 'LOOPBACK_BIND_HOSTS', 'MCP_EVENT_CONTEXT_ENV',
    'PACKAGE_DIR', 'PATH_LIKE_ENV_KEYS', 'PERSISTENCE_ERROR_CODES', 'Path',
    'PersistenceContractError', 'PurePosixPath', 'REDACTION_MARKER', 'RUNTIME_ID_INVALID',
    'RUNTIME_ID_PATTERN', 'RUNTIME_ID_PATTERN_TEXT', 'RUNTIME_LOG_REL', 'RuntimeIdValidationError',
    'SCAFFOLD_PLACEHOLDER_PATTERN', 'SCRIPTS_DIR', 'SCRIPT_DIR', 'SECRET_KEY_PATTERN',
    'SESSION_ACTIVE_STATUS', 'SESSION_SCHEMA_VERSION', 'SESSION_TERMINAL_STATUSES', 'SHA256_HEX_PATTERN',
    'SHARED_SKILL_ASSET_DIR', 'SKILL_REPOS_CONFIG_VERSION', 'SKILL_REPOS_LOCKFILE_VERSION', 'StateLockTimeout',
    'VALID_ARTIFACT_SOURCE_KINDS', 'VALID_ARTIFACT_SYNC_MODES', 'VALID_CHECK_TYPES', 'VALID_ENV_FILE_SOURCE_KINDS',
    'VALID_ENV_FILE_SYNC_MODES', 'VALID_HEALTHCHECK_TYPES', 'VALID_REPO_SOURCE_KINDS', 'VALID_SKILL_SYNC_MODES',
    'VALID_SYNC_MODES', 'VALID_TASK_SUCCESS_TYPES', 'WILDCARD_BIND_HOSTS', 'WORKER_BROKER_MCP_SURFACES',
    'WORKER_CONTEXT_UNRESOLVED', 'WORKER_DEFAULT_ARTIFACT_POLICY', 'WORKER_DEFAULT_LAUNCH_TIMEOUT_SECONDS', 'WORKER_DEFAULT_MEMORY_SCOPE',
    'WORKER_DEFAULT_RUNTIME_ID', 'WORKER_DEFAULT_WRITE_SCOPE', 'WORKER_ERROR_CODES', 'WORKER_LAUNCH_FAILED',
    'WORKER_LAUNCH_SETTLE_SECONDS', 'WORKER_LEARNING_REVIEW_REQUIRED', 'WORKER_MEMORY_SCOPES', 'WORKER_POLICY_BLOCKED',
    'WORKER_RESULT_NOT_READY', 'WORKER_RUNTIME_IDS', 'WORKER_RUNTIME_UNKNOWN', 'WORKER_RUN_ID_PATTERN',
    'WORKER_RUN_NOT_FOUND', 'WORKER_RUN_SCHEMA_VERSION', 'WORKER_RUN_STATES', 'WORKER_TASK_CLASSES',
    'WORKER_TERMINAL_STATES', 'WORKER_WRITEBACK_REJECTED', 'WORKER_WRITE_SCOPES', 'WorkerRun',
    'WorkerRuntimeError', 'WorkerTaskSpec', '_ATOMICITY_COUNTER_ENV', '_ATOMICITY_KILL_AT_ENV',
    '_COMMAND_FALLBACK_NEXT_ACTIONS', '_STATE_LOCK_POLL_INTERVAL_SECONDS', '_STATE_LOCK_WAIT_WARN_SECONDS', '_WORKER_ACTIVE_PROCESSES',
    '__annotations__', '__builtins__', '__cached__', '__doc__',
    '__file__', '__loader__', '__name__', '__package__',
    '__spec__', '_add_overlay_projection_files', '_add_packaged_skillset_projection_files', '_add_projection_optional_root_files',
    '_add_projection_runtime_manifest', '_add_projection_skillset_files', '_add_skill_repo_set_projection_files', '_append_jsonl',
    '_atomic_write_json_serialized', '_atomicity_checkpoint', '_atomicity_checkpoint_count', '_build_lock_skill_entry',
    '_checkout_skill_repo_ref', '_classify_message_pattern', '_classify_persistence_error', '_clone_new_skill_repo',
    '_clone_or_fetch_repo', '_current_skill_repo_commit', '_durable_session_event_paths', '_durable_session_event_payload',
    '_ensure_client_exists', '_ensure_worker_proposal_promotable', '_ensure_worker_write_scope_allowed', '_event_matches_scope',
    '_fetch_existing_skill_repo', '_find_worker_learning_proposal', '_flock_unsupported_warned', '_fsync_directory',
    '_generate_session_id', '_generate_worker_run_id', '_host_skill_mirror_root', '_install_shared_skill_asset_to_targets',
    '_install_skill_to_targets', '_iter_jsonl_dicts', '_iter_worker_run_paths', '_launch_worker_if_ready',
    '_load_durable_session_meta', '_load_skillignore', '_mark_worker_proposal_promoted', '_matches_skillignore',
    '_mirror_installed_skill_to_host_home', '_normalize_session_event_type', '_normalize_worker_choice', '_normalize_worker_client_id',
    '_normalize_worker_promotion_mode', '_normalize_worker_run_id', '_normalize_worker_runtime', '_persist_session_event',
    '_persist_skill_repo_lockfile', '_persist_worker_payload', '_projection_runtime_model_payload', '_pull_skill_repo_branch',
    '_read_session_events', '_read_session_meta', '_reconcile_host_skill_mirrors', '_reconcile_worker_payload',
    '_recover_interrupted_tree_swap', '_reject_pending_worker_proposal', '_resolve_skill_dirs', '_resolve_skill_repo_entry_source',
    '_resolve_worker_context', '_runtime_log_timestamp', '_session_event_roots', '_session_now',
    '_session_payload', '_session_subject', '_shared_skill_asset_source', '_skill_repo_lock_skill_names',
    '_state_lock_age_seconds', '_symlink_points_inside', '_warn_flock_unsupported', '_worker_apply_terminal_from_launch_paths',
    '_worker_apply_terminal_result', '_worker_client_id_from_cwd', '_worker_client_index', '_worker_client_match_paths',
    '_worker_effective_cwd', '_worker_hermes_command', '_worker_launch_env', '_worker_launch_paths',
    '_worker_launch_pid', '_worker_launch_timeout_seconds', '_worker_learning_review_required', '_worker_loaded_result',
    '_worker_mark_launch_failed', '_worker_mark_launching', '_worker_mark_running', '_worker_now',
    '_worker_path_contains', '_worker_payload_state', '_worker_pid_running', '_worker_promotion_response',
    '_worker_proposal_status', '_worker_proposal_target_matches', '_worker_reap_active_process', '_worker_repo_id',
    '_worker_resolved_context', '_worker_result_payload', '_worker_safe_path', '_worker_stderr_tail',
    '_worker_summary_artifact', '_write_session_handoff', 'add_projection_source_file', 'add_projection_source_tree',
    'add_projection_text_file', 'annotations', 'append_client_session_event', 'argparse',
    'artifact_source_configured', 'asdict', 'atomic_replace_tree', 'atomic_write_bytes',
    'atomic_write_json', 'atomic_write_text', 'base_client_overlay', 'build_blueprinted_client_scaffold_files',
    'build_projected_runtime_manifest', 'build_runtime_model', 'bundle_members', 'bundle_metadata',
    'classify_bind_scope', 'classify_error', 'client_blueprint_dir', 'client_config_host_dir',
    'client_config_runtime_dir', 'client_configs_host_root', 'client_context_location', 'client_overlay_location',
    'client_plan_seed_files', 'client_planning_skill_template_root', 'client_scaffold_keep_files', 'client_scaffold_local_skills_dir',
    'client_scaffold_pack', 'client_scaffold_pack_required_skills', 'client_scaffold_pack_skill_templates', 'client_scaffold_seed_files',
    'client_scaffold_shared_skills_dir', 'client_scaffold_skill_repo_entries', 'client_skill_builder_seed_files', 'client_skill_builder_template_root',
    'clone_dir_name', 'collect_client_projection_files', 'compile_persistence_summary', 'context_output_paths',
    'copy', 'copy_tree_atomic', 'create_worker_run', 'current_mcp_event_context',
    'dataclass', 'datetime', 'default_client_scaffold_files', 'digest_bytes',
    'directory_file_entries', 'directory_tree_sha256', 'emit_json', 'end_client_session',
    'ensure_client_overlay_context_shape', 'ensure_client_overlay_scaffold_shape', 'ensure_client_overlay_skillset_shape', 'ensure_client_scaffold_skill_sources',
    'ensure_directory', 'ensure_git_repo', 'event_feed_payload', 'extract_command_port',
    'extract_host_port', 'fcntl', 'file_sha256', 'filtered_copy_skill',
    'find_duplicates', 'format_profile_args', 'git_dirty_paths', 'git_head_commit',
    'hashlib', 'host_path_to_absolute_path', 'human_bytes', 'inferred_private_target_dir',
    'init_private_repo', 'is_elevated_pressure_level', 'is_secret_key', 'json',
    'json_or_none', 'list_client_blueprints', 'list_client_sessions', 'load_client_blueprint',
    'load_client_projection_bundle', 'load_json_file', 'load_runtime_env', 'load_skill_repos_config',
    'load_yaml', 'locked_json_update', 'log_runtime_event', 'managed_home_install_targets',
    'materialize_client_projection', 'merge_client_overlay', 'merge_runtime_event_detail', 'migrate_client_overlay_tree',
    'migrate_client_subtree', 'next_actions_for_acceptance_mcp_failure', 'next_actions_for_acceptance_success', 'next_actions_for_bootstrap',
    'next_actions_for_client_diff', 'next_actions_for_client_init', 'next_actions_for_client_open', 'next_actions_for_client_project',
    'next_actions_for_client_publish', 'next_actions_for_context', 'next_actions_for_doctor', 'next_actions_for_down',
    'next_actions_for_first_box', 'next_actions_for_focus', 'next_actions_for_private_init', 'next_actions_for_session_end',
    'next_actions_for_session_event', 'next_actions_for_session_resume', 'next_actions_for_session_start', 'next_actions_for_session_status',
    'next_actions_for_status', 'next_actions_for_sync', 'next_actions_for_up', 'normalize_bundle_rel_path',
    'normalize_client_connector_entries', 'normalize_client_overlay_shape', 'normalize_host_rel_path', 'normalize_sha256',
    'os', 'parse_key_value_assignments', 'parse_runtime_log_line', 'prepare_client_projection_output_dir',
    'pressure_advisory_warning_messages', 'project_client_bundle', 'promote_worker_learning', 're',
    'read_client_session', 'read_durable_session_events', 'read_json_tolerant', 'read_manifest_skills',
    'read_runtime_log_events', 'read_worker_run', 'redact_text', 'redact_value',
    'remove_path', 'render_client_plan_index', 'render_client_scaffold_skill_repos', 'render_skill_builder_extraction_rule',
    'render_skill_builder_index', 'render_yaml_document', 'repo_rel', 'require_yaml',
    'resolve_client_blueprint_path', 'resolve_client_log_root', 'resolve_client_open_output_dir', 'resolve_client_projection_output_dir',
    'resolve_client_publish_bundle_dir', 'resolve_client_publish_target_dir', 'resolve_client_session_root', 'resolve_context_dir',
    'resolve_known_placeholders', 'resolve_optional_host_dir', 'resolve_root_dir', 'resume_client_session',
    'run_command', 'runtime_manifest_path', 'runtime_path_to_host_path', 'runtime_path_to_projection_rel_path',
    'sanitize_projection_env', 'sanitize_projection_source', 'sanitize_projection_value', 'scaffold_client_overlay',
    'scaffold_connector_entries', 'selectors', 'session_paths', 'session_status_payload',
    'shlex', 'shutil', 'signal', 'split_csv_values',
    'start_client_session', 'storage_binding_by_id', 'structured_error', 'subprocess',
    'sync_client_scaffold_seed_files', 'sync_skill_repo_sets', 'sys', 'tempfile',
    'time', 'titleize_client_id', 'tree_hash', 'unique_string_field_values',
    'upsert_env_file_values', 'urllib', 'validate_client_id', 'validate_runtime_id',
    'validate_url_download_source', 'walk_values', 'worker_artifacts_payload', 'worker_run_paths',
    'worker_runs_root', 'worker_runtime_error_payload', 'worker_status_payload', 'write_json_file',
    'write_text_file', 'yaml', 'zipfile',
)


class _SharedModule(_types.ModuleType):
    def __setattr__(self, name: str, value: Any) -> None:
        super().__setattr__(name, value)
        for module in _SHARED_LEAF_MODULES:
            if hasattr(module, name):
                setattr(module, name, value)

    def __delattr__(self, name: str) -> None:
        super().__delattr__(name)
        for module in _SHARED_LEAF_MODULES:
            if hasattr(module, name):
                delattr(module, name)


def __dir__() -> list[str]:
    return list(_SHARED_DIR_BASELINE)


sys.modules[__name__].__class__ = _SharedModule
